---

- block:
  - name: Waiting for microk8s to be ready on microk8s host master
    command: "microk8s status --wait-ready"
    hosts: main
    delegate_facts: true
    changed_when: false

  - name: Get the microk8s join command from the microk8s master
    shell: "microk8s.add-node --format json"
    hosts: main
    delegate_facts: true
    changed_when: false
    register: microk8s_join_output

  - name: Get microk8s cluster nodes
    command: "microk8s kubectl get node"
    hosts: main
    delegate_facts: true
    changed_when: false
    register: microk8s_cluster_node

  - name: Waiting for microk8s to be ready on microk8s worker node
    command: "microk8s status --wait-ready"
    changed_when: false
    register: status_command_output
    failed_when:
      - "'This MicroK8s deployment is acting as a node in a cluster.' not in status_command_output.stdout_lines"
      - status_command_output.rc > 0

  - name: Set the microk8s join command on the microk8s node
    command: "microk8s join {{ (microk8s_join_output.stdout | from_json).urls[0] }}"
    when: microk8s_cluster_node.stdout.find(inventory_hostname) == -1
    register: join_command_output
    failed_when:
      - "'already known to dqlite' not in join_command_output.stdout"
      - join_command_output.rc > 0

  become: yes
  when:
    - inventory_hostname in groups[nodes]
